INSERT INTO healthday_topic (topic_name, topic) VALUES ('ALS (Lou Gehrig''s Disease)', 'ALS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Abortion', 'ABOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Acne', 'ACNE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Activase', '=ACT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Acupuncture', 'PUNC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Addiction', 'ADCT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Age', 'AGE-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Age Quotient: High', 'HIAQ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Age Quotient: Low', 'LOAQ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Aging: Misc', 'AGNG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Alcohol & Kids', 'KALC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Alcohol Abuse', 'ALCA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Alcohol: Misc', 'ALCO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Alcohol: Teetotaling', 'TTOT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Allegra', '=ALL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Allergies: Food', 'FDAL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Allergies: Misc', 'ALLR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Allergies: Nasal', 'NZAL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Alternative Medicine: Misc', 'ALTM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Alzheimer''s', 'ALZH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ambien', '=AMB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Amblyopia (Lazy Eye)', 'AMBL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Anaphylactic Shock', 'ANAP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Anatomy / Biology', 'ANAT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Anemia', 'ANEM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Angioplasty', 'ANGI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ankylosing Spondylitis', 'ANKY');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Anorexia', 'ANOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Anosmia (Poor Sense Of Taste Or Smell)', 'ANOZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Antibiotics', 'ANTB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Antihistamines', 'ANTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Antioxidants', 'ANTO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Anxiety', 'ANXI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Aphrodisiacs', 'APHR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Appendicitis', 'APPX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Aromatherapy', 'AROM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Arthritis: Demographics', 'ARTG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Arthritis: Diet', 'ARTN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Arthritis: Drugs', 'ARTD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Arthritis: Management', 'ARTM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Arthritis: Misc', 'ARTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Arthritis: Osteo', 'OSTA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Arthritis: Rheumatoid', 'RHAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Artificial Hips', 'AHIP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Artificial Knees', 'AKNE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Aspirin', 'ASPR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Asthma', 'ASTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Athlete''s Foot', 'ATHF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Atrovent', '=ATR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Attention Deficit Disorder (ADHD)', 'ADHD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Autism', 'AUTI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Axid', '=AXI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Backache', 'BACH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bad Breath', 'BADB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bedwetting', 'BEDW');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Behavior', 'BHVR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Beta Carotene', 'BCAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Biofeedback', 'BIOF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Biotechnology', 'BTEC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bipolar Affective Disorder', 'BIPO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Birth', 'BORN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Birth Control', 'BIRC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Birth Defects: Misc', 'BIRD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Birthday', 'BDAY');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bites & Stings', 'BITE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bladder Infections', 'BLNF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Blindness', 'BLND');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Blood Disorders', 'BLOO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Blood Glucose Monitors', 'BGLU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Blood Pressure', 'BLPR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Body Building', 'BBLD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bone / Joint / Tendon Problems', 'BONE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Botox', 'BOTX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bowel Problems: Colostomy', 'COLS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bowel Problems: Diverticulosis Or Diverticulitis', 'DIVT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bowel Problems: Gas', 'GAS-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bowel Problems: Gastritis', 'GAST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bowel Problems: Inflammatory Bowel Disease', 'IBD-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bowel Problems: Misc', 'BOWE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Brain', 'BRAI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Breast Reduction', 'BRED');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Breast-Feeding', 'FEED');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bronchitis', 'BRON');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bruises', 'BRUI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bulimia', 'BULI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Bunions', 'BUNI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Burns', 'BURN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('CAT Scans', 'CATS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Caffeine / Coffee / Tea', 'CAFF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Calan', '=CAL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Bladder', '-BLA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Bone', '-BON');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Brain', '-BRN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Breast', '-BRS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Cervical', '-CER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Colon', '-COL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Esophageal', '-ESO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Laryngeal', '-LAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Leukemia', '-LEU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Lung', '-LUN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Lymphoma', '-LYM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Misc', '-GEN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Mouth', '-MOU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Ovarian', '-OVA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Pancreatic', '-PAN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Prostate', '-PRO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Rectal', '-REC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Skin', '-SKI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Testicular', '-TST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Throat', '-THR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cancer: Uterine', '-UTR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Capoten', '=CAP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cardizem', '=CZM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cardura', '=CRD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Carpal Tunnel Syndrome', 'CARP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cataracts', 'CATR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Caverject', '=CAV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cavities', 'CAVI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Celebrex', 'CBX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Centers for Disease Control', 'CDC-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cerebral Palsy', 'PALS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Chemotherapy', 'CHEM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Chickenpox', 'CHPX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Child Development', 'CDEV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Child Psychology', 'CPSY');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Childbirth', 'CHBR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Chinese Medicine', 'CHIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Chiropractic', 'CHIR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Chlamydia', 'CHLA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cholesterol: Dietary', 'CHOD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Circumcision', 'CIRC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cirrhosis', 'CIRR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Claritin', '=CLA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cleft Lip / Palate', 'CLEF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Climara', '=CLI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Clinical Trials', 'CLIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cloning', 'CLON');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cognex', '=COG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Colic', 'COLI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Colonoscopy', 'COLN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Color Blindness', 'CBLI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Common Cold', 'COLD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computer-Related', 'CPUI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet', 'CMPU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: America Online', 'AOL-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: Compuserve', 'COMP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: Internet Service Provider', 'ISP-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: Microsoft Network', 'MSN-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: Misc', 'ONLN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: Prodigy', 'PRODI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: Remedy Online', 'REMD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Computers / Internet: Search Engines', 'SRCH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Condoms', 'COND');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Conjunctivitis (Pink Eye)', 'CONJ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cooking / Recipes', 'COOK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cosmetic Surgery', 'CSUR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cosmetics', 'COSM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Coughs', 'COUG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cozaar', '=COZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cradle Cap', 'CCAP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cramps', 'CRMP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cramps: Menstrual', 'CMEN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cramps: Muscle', 'CMUS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Crohn''s Disease', 'CROH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cuts & Scratches', 'CUTS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cystic Fibrosis', 'CF--');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Cysts', 'CYST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('DNA', 'DNA-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dandruff', 'DAND');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Daypro', '=DAY');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Death & Dying: Misc', 'DEAD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Demographics', 'DEMO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dental Problems: Misc', 'DENT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dentures', 'FALS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Depression', 'DEPR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Demographics', 'DIAG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Diet', 'DIAN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Drugs', 'DIAD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Management', 'DIAM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Misc', 'DIAB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Type I', 'DIA1');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Type II', 'DIA2');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diabetes: Types', 'DIAT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diaper Rash', 'DIAP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diarrhea', 'DIAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diet Drugs', 'DDRU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Avoid Caffeine', 'DCAF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Avoid Lactose Or Milk', 'DLAC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Control Cholesterol', 'DCHO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Control Salt', 'DSOD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Gain Or Maintain Weight', 'DGOM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Gain Weight', 'DGAI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Increase Fiber', 'DFBR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Lose Weight', 'DLOS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Lower Fat Intake', 'DFAT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Maintain Weight', 'DMAI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dieting To Reduce Sugar', 'DSUG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diflucan', '=DIF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Digestion', 'DIGE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dilation & Curettage (D & C)', 'DILC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Disabled / Special Needs', 'SPEC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Diseases & Conditions: Misc', 'DISE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Divorce', 'DIVC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dizziness/Vertigo', 'DIZZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Doctors', 'DOCS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Domestic Violence', 'DOMV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dose Adjusting', 'DOSE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Down Syndrome', 'DOWN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drug Abuse', 'DRAB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drug Abuse: Effects', 'DRUE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drug Abuse: Social Issues', 'DRUS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drug Abuse: Treatment / Solutions', 'DRUT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drug Approvals', 'RXOK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drug Interactions', 'DINT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drugs & Kids', 'KDRU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drugs: Illicit', 'IDRU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drugs: Misc', 'DRUG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Drunk Driving / Riding', 'DRDR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Dyslexia', 'DYSL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ear / Nose / Throat', 'ENTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ear Infections', 'EARI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Eating / Appetite Disorders', 'EATD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Economic Status', 'ECON');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Effexor', '=EFF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Elbow Problems', 'ELBO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Emergencies / First Aid', 'EMER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Emotional Disorders: Misc', 'EMOT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Emphysema', 'EMPH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Encephalitis', 'ENCP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Endocrinology', 'ENDC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Endometriosis', 'ENDO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Environment', 'ENVR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Environmental Medicine', 'ENVM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Epilepsy', 'EPIL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Estrace', '=EST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Estraderm', '=ESD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Estrogen', 'ESTR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Aerobics Or Calisthenics', 'AERO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Baseball Or Softball', 'BALL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Basketball', 'BASK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Bowling', 'BOWL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Canoeing Or Kayaking Or Rowing', 'CANU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Climbing', 'CLIM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Cycling', 'CYCL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Dancing', 'DANC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Diving, Board Or Platform', 'DIVE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Diving, Skin', 'DIVS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Fencing', 'FENC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Football', 'FBAL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Gardening', 'GARD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Golf', 'GOLF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Gym', 'GYMX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Gymnastics', 'GYMN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Handball', 'HNDB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Hiking Or Backpacking', 'HIKE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Hockey, Field', 'FHOC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Hockey, Ice', 'HOCK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Home', 'HOMX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Horseback Riding', 'HORS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Jogging Or Running', 'JRUN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Lacrosse', 'LACR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Machine', 'MCHX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Martial Arts', 'MART');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Misc', 'EXER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Paddleball', 'PADL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Ping Pong Or Table Tennis', 'PONG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Racquetball', 'RACQ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Rope Skipping', 'SKIP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Sailing', 'SAIL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Shuffleboard', 'SHUF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Skating, Ice', 'SKAT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Skating, Inline Or Roller', 'ROLL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Skiing, Cross-Country', 'XSKI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Skiing, Downhill Or Snowboarding', 'DSKI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Skiing, Water', 'WSKI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Soccer', 'SOCC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Spinning', 'SPNG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Squash', 'SQUA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Stepping', 'STEP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Surfing', 'SURF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Swimming', 'SWIM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: T''ai Chi Or Oriental', 'TCHI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Tennis', 'TENN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Trampolining', 'TRAM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Treadmill', 'MILL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Volleyball', 'VOLL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Walking', 'WALK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Water Exercise', 'WTRX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Weight Lifting', 'LIFT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Windsurfing', 'WIND');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Wood Chopping Or Sawing', 'WOOD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Wrestling', 'WRES');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Exercise: Yoga', 'YOGA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Eye / Vision Problems: Misc', 'EYES');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Eye Drops', 'EYDR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Face-Lifts', 'FACE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fat Substitutes', 'FSUB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fat, Body', 'BFAT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fat, Dietary', 'FAT-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fatherhood', 'FATH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fatigue', 'FATI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fears / Phobias', 'FEAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Feldene', '=FEL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Feminine Products', 'FEMP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fever', 'FEVR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fiber, Dietary', 'FIBR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fibroids', 'FBRD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fibromyalgia', 'FMYA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fitness Equipment', 'FTEQ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fitness: Misc', 'FITN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Floaters (Eye)', 'FLOA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Flu', 'FLU-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Food & Drug Administration', 'FDA-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Food & Nutrition: Misc', 'FOOD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Food Additives', 'FADD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Food Irradiation', 'FDIR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Food Poisoning', 'FOOP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Foot Problems: Misc', 'FOOT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fosamax', '=FOS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fractures', 'FRAC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Frequent Dry Mouth', 'DRYM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Friendship', 'FRND');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Frostbite', 'FROS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Funerals', 'FUNR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Fungal Infections', 'FUNG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Gallbladder Problems: Misc', 'GALL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Gallstones', 'GSTO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Gastrointestinal Problems', 'GASI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Gene Therapy', 'GTHR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Genetic Disorders', 'GENE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Genetically Altered Food', 'GENF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Genetics', 'GENT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Glaucoma', 'GLAU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Glucophage', '=GLU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Gonorrhea', 'GONO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Gout', 'GOUT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Government', 'GOVT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Grave''s Disease', 'GRAV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hair And Scalp Problems: Misc', 'HAIR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hair Loss', 'BALD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hammertoes', 'HTOE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Head Injuries', 'HEAD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Headaches', 'HACH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Health Biz: Misc', 'HBIZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Health Clubs', 'CLUB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Health Costs', 'COST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Health Quizzes', 'QUIZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hearing Aids', 'HAID');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hearing Disorders: Misc', 'HEAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hearing Loss', 'DEAF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related Problems: Stroke', 'STRO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: Aneurysm', 'ANEU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: Angina', 'ANGN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: Coronary-Artery Disease', 'CORA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: Heart Attack', 'HATT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: High Blood Pressure', 'HIBP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: High Cholesterol', 'HICH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: Misc', 'HRTS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart / Stroke-Related: Rheumatic Heart Disease', 'RHHD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart Attack: Demographics', 'HRTG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart Attack: Diet', 'HRTN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart Attack: Drugs', 'HRTD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart Attack: Management / Prevention', 'HRTM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart Attack: Symptoms / Warning Signs / Risks', 'HRTW');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart Bypass', 'HBYP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heart Pacemakers', 'PACE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heartburn / GERD / Indigestion', 'GERD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Heat- / Sunstroke', 'HEAT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hemophilia', 'HEMO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hemorrhoids', 'HEMR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hepatitis', 'HEPA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Herbal Medicine', 'HERB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hernia', 'HERN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Herpes Simplex (Genital)', 'HSIM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Herpes Zoster (Shingles)', 'HZOS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hiccups', 'HICC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('High Mileage', 'HIMI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hismanal', '=HIS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('History of Medicine', 'HIST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hives', 'HIVE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Holistic Medicine', 'HOLI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Home Healthcare', 'HHCR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Homeopathy', 'HMEO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Homosexuality', 'HOMO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hormone Replacement Therapy', 'HRT-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hormones: Female', 'FHOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hormones: Male', 'MHOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hormones: Misc', 'HORM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hormones: Thyroid', 'THOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hospices', 'HSPC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hospitals', 'HOSP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Humulin', '=HUM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Huntington''s Disease', 'HUNT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hygiene', 'HYGI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hyperactivity', 'HYPR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hypnosis', 'HYPN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hysterectomy', 'HYST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Hytrin', '=HYT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Imaging Devices', 'IMAG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Imitrex', '=IMI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Imitrex Oral', '=IMO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Immune Disorders', 'IMMN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Immunization', 'IMMU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Impetigo', 'IMPE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Implants', 'IMPL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Impotence', 'IMPO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Incontinence', 'INCO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Infant / Child Care', 'BABC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Infections: Misc', 'INFC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Infertility', 'INFR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Injuries', 'INJU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insulin', 'INSU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Blue Cross / Blue Shield', 'BLUE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Disability', 'DISA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: HMOs', 'HMOS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Lack Of', 'NINS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Life', 'LIFI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Long-Term Care', 'LTRM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Medicaid', 'MAID');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Medicare', 'MEDC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Medicare + Private Insurance', 'MPRI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Misc', 'INSR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: PPOs', 'PPOS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Private', 'PINS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Insurance: Veterans / CHAMPUS', 'VETS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Irregularity / Constipation', 'IRRG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Jaw Problems', 'JAWP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Jock Itch', 'JOCK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Kidney Cancer', '-KID');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Kidney Problems: Misc', 'KIDN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Kidney Stones', 'KSTN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Kids'' Ailments', 'KAIL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Kids: Misc', 'KIDS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Knee Problems', 'KNEE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lactose Intolerance', 'LACT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Laryngitis', 'LARN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lasers / Laser Surgery', 'LASR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Laxatives', 'LAXA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Learning Disabilities: Misc', 'LERN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lescol', '=LES');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lice: Crab', 'CRAB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lice: Head', 'LICE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Liposuction', 'LIPO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Liver', '-LIV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Liver Disease: Misc', 'LIVR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lodine', '=LOD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Looks: Misc', 'LOOK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lotensin', '=LTN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lotrel', '=LTR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Love / Sex / Relationships: Misc', 'LOVE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lupus', 'LUPS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Lyme Disease', 'LYME');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('MRI Scans', 'MRI-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Macrobiotics', 'MACR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Macular Degeneration', 'MACD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mail-Order Drugs', 'MAIL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Malaria', 'MALA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mammography', 'MAMO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Manic Depression', 'MANC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Marriage', 'MARG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Massage', 'MASS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Measles', 'MEAS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Medical Myths', 'MYTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Medical Technology: Misc', 'TECH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Meditation', 'MEDT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Memory Problems', 'MEMO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Men''s Problems: Misc', 'MENS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Meniere''s Disease', 'MENR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Meningitis', 'MNNG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Menopause / Postmenopause', 'MENO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Menstruation', 'MNST');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mental Illness / Retardation', 'MENT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mevacor', '=MEV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Miacalcin', '=MIA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Migraine', 'MIGR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Miscarriage', 'MSCG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Miscellaneous: Misc', 'MISC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mitral Valve Prolapse', 'MITR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mobility / Balance Problems', 'MOBI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mononucleosis', 'MONO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Monopril', '=MON');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Motherhood', 'MOTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Motion Sickness', 'MSIC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Multiple Sclerosis', 'MSC-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Mumps', 'MUMP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Muscle Problems', 'MUSC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Muscular Dystrophy', 'MUSD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Myasthenia Gravis', 'MYAS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Myopia (Nearsightedness)', 'MYOP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('National Institues of Health', 'NIH-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Naturopathy', 'NATU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Neck Problems', 'NECK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Nerve Disorders', 'NERV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Neurology', 'NEUR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Night Blindness', 'NITE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Norvasc', '=NOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Nose Bleeds', 'NBLD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Nose Surgery', 'NSUR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Nursing Homes / Elder Care', 'NHOM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Nutrition Score: High', 'HNUT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Nutrition Score: Low', 'LNUT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Nutritional Supplements', 'NSUP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Obesity', 'OBES');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Obsessive-Compulsive Disorders', 'OBCO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Occupational Health', 'OCCU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Organ Donation', 'ORGN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Organ Transplants', 'ORGT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Orgasm', 'ORGZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Orthodontics', 'BRAC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Orthomolecular Medicine', 'ORTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Osteopathy', 'OSTY');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Osteoporosis', 'PORO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Over-The-Counter Drugs: Misc', 'OTC-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Overweight / Underweight', 'OUWT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Overweight Kids', 'KOVR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ovulation', 'OVUL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('PMS', 'PMS-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pain', 'PAIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Panic Attacks', 'PNIC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pap Smears', 'PAPS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Paralysis', 'PARA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Parasites: Misc', 'PARS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Parenting', 'PRNT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Parkinson''s', 'PARK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Paxil', '=PAX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Peak-Flow Meters', 'FLOW');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pepcid', '=PEP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Perspiration', 'PRSP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pets And Health', 'PETS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Physical Therapy', 'PTHR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pituitary', 'PITU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Placebos', 'PLAC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pneumoconiosis', 'CONI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pneumonia', 'PNEU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Poisons', 'POIS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Polarity Therapy', 'POLA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Polio', 'POLI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pollution, Air', 'APOL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pollution, Water', 'WPOL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pravachol', '=AVA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pregnancy', 'PREG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pregnancy: Diet', 'PREN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pregnancy: Drugs', 'PRED');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pregnancy: Risks', 'PRER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Pregnancy: Teens', 'PRET');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Premarin', '=MAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prempro', '=EMP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Presbyopia', 'PRSB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prescription Drugs', 'PRES');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Press, Medical / Health Reporting', 'PRSS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prevacid', '=EVA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prilosec', '=ILO');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Procardia', '=CAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Product Recalls', 'RCLS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Propulsid', '=PUL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Proscar', '=SCR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prostate Problems', 'PROS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prostate Problems: Diet', 'PRON');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prostate Problems: Drugs', 'PROD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prostate Problems: Management', 'PROM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prostheses: Misc', 'PRTH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Proventil', '=PRV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Prozac', '=ZAC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Psychology / Mental Health: Misc', 'PSYC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Puberty', 'PUBE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Quackery / Hype', 'QUAC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Rabies', 'RABI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Race', 'RAC-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Radiation', 'RADI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Rashes', 'RASH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Raynaud''s Disease', 'RAYN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Reference', 'REFR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Relafen', '=REL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Relaxation Therapy', 'RLAX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Religion', 'RELI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Research & Development', 'RSRC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Respiratory Problems: Flu Or Pneumonia', 'FLUP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Respiratory Problems: Misc', 'RESP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Retirement Planning', 'RETR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Reye''s Syndrome', 'REYE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ringworm', 'RWRM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ritalin', '=RIT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Safety & Public Health', 'SAFP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Safety & Public Health: Misc', 'SAFE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Safety: Child', 'CHIS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Safety: Fire', 'FIRS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Safety: Food', 'FOOS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Safety: Water', 'WTRS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Salt / Sodium', 'SALT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Scabies', 'SCAB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Schizophrenia', 'SCHZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sciatica', 'SCIA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Scoliosis', 'SCOL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Seasonal Affective Disorder (SAD)', 'SAD-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Seat Belts', 'BELT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sedatives', 'SEDT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Seizures', 'SEIZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Seldane', '=SEL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sensory Problems', 'SENS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Serzone', '=SER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sex', 'SEX-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sex: Abuse / Rape', 'SEXA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sex: Children / Teens', 'SEXK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sex: Disorders', 'SEXI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sexually Transmitted Diseases: AIDS/HIV', 'AIDS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sexually Transmitted Diseases: Herpes, Genital', 'HERP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sexually Transmitted Diseases: Misc', 'STD-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Shin Splints', 'SHIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Shoes', 'SHOE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sickle-Cell Anemia', 'SIKL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Singlehood', 'SING');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sinus Problems', 'SINU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Site Reviews', 'SITE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Care', 'SKCR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Disorders: Dry Skin', 'DRSK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Disorders: Eczema', 'ECZM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Disorders: Itchiness', 'ITCH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Disorders: Misc', 'SKIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Disorders: Psoriasis', 'PSOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Disorders: Rosacea', 'ROSA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Skin Disorders: Warts', 'WART');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sleep Problems: Apnea', 'APNE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sleep Problems: Insomnia', 'SOMN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sleep Problems: Misc', 'SLEE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sleep Problems: Snoring', 'SNOR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Smoking Cessation', 'NSMK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sore Throat', 'SORE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Speech Disorders', 'SPCH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Speeding', 'SPEE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Spina Bifida', 'BIFI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Spinal Problems', 'SPIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sports Medicine', 'SPMD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sprains', 'SPRN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Stem Cells', 'STEM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Steroids', 'STER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Stomach Trouble', 'STOM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Strep Infections', 'STRP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Stress', 'STRS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Stuttering', 'STUT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Stye', 'STYE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sudden Infant Death Syndrome (SIDS)', 'SIDS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sugar', 'SUGR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sugar Substitutes', 'SUGS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Suicide', 'SUIC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sunburn / Tan', 'SUNB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Sunscreens / Lotions', 'SSCR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Support Groups', 'SUPP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Surgery: Misc', 'SURG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Syphilis', 'SYPH');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tagamet', '=TAG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tapeworm', 'TAPE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tay-Sachs Disease', 'TAYS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Teen Sex / Pregnancy', 'TSEX');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Teething', 'TEET');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tetanus', 'TETN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Therapy & Procedures: Misc', 'THER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Thyroid', 'THYD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Timoptic', '=TIM');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tinnitus', 'TINN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tobacco & Kids', 'KTOB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tobacco: Chewing Or Snuff', 'CHEW');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tobacco: Cigar Smoking', 'CGAR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tobacco: Cigarette Smoking', 'CIGS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tobacco: Misc', 'TOBA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tobacco: Pipe Smoking', 'PIPE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Toilet Training', 'TOIL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tonsillitis', 'TONS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tooth Whitening', 'TOOW');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Trauma', 'TRAU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Medicine', 'TRMD');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Safety: Midsize Car Or Minivan', 'MSIZ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Safety: Misc', 'TRVS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Safety: Motor Vehicle Injury', 'VINJ');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Safety: Motorcycle', 'MCYC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Safety: Sport/Utility Vehicle', 'SUV-');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Safety: Subcompact Or Compact', 'SUBC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel Safety: Truck Or Full-Size Van', 'TRUK');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel: Abroad', 'TRAB');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel: Misc', 'TRAV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Travel: U.S.', 'TRUS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Tuberculosis', 'TUBR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ulcers', 'ULCR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ultram', '=ULT');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Urinary Tract Infections', 'URNF');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Urine Problems', 'URIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Uterine Problems', 'UTER');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Vaccines', 'VACC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Vaginal Problems', 'VAGI');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Varicose Veins', 'VEIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Vasectomy', 'VSEC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Vasotec', '=VAS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Vegetarianism', 'VEGE');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Ventolin', '=VEN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Viagra', 'VIA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Viruses', 'VIRU');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Vitamins / Minerals', 'VITA');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Vivelle', '=VIV');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Voltaren', '=VOL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Water Consumption', 'WATR');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Weight Gain', 'GAIN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Weight Loss', 'LOSS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Weight: Misc', 'WEIG');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Widowhood', 'WIDW');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Wills', 'WILL');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Women''s Problems: Misc', 'WMEN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Women''s Health', 'WMGP');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('X-Rays', 'XRAY');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Yeast Infections', 'YEAS');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Zantac', '=ZAN');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Zocor', '=ZOC');
INSERT INTO healthday_topic (topic_name, topic) VALUES ('Zoloft', '=ZOL');
